export const FRIENDS_FETCH_START = `FRIENDS_FETCH_START`;
export const FRIENDS_FETCH_SUCCESS = `FRIENDS_FETCH_SUCCESS`;
export const FRIENDS_FETCH_FAILURE = `FRIENDS_FETCH_FAILURE`;

export const FRIENDS_CREATE_START = `FRIENDS_CREATE_START`;
export const FRIENDS_CREATE_SUCCESS = `FRIENDS_CREATE_SUCCESS`;
export const FRIENDS_CREATE_FAILURE = `FRIENDS_CREATE_FAILURE`;

export const FRIENDS_EDITING_START = `FRIENDS_EDITING_START`;
export const FRIENDS_UPDATE_START = `FRIENDS_UPDATE_START`;
export const FRIENDS_UPDATE_SUCCESS = `FRIENDS_UPDATE_SUCCESS`;
export const FRIENDS_UPDATE_FAILURE = `FRIENDS_UPDATE_FAILURE`;
